#!/bin/bash
./app_da.py -i ./../data/20150503/BP/CDS-7-BP.csv -g ./../result/BP_descendant_ancestor.csv -c BP-GOTERM.txt -t goterm
./app_da.py -i ./../data/20150503/BP/CDS-H1-BP.csv -g ./../result/BP_descendant_ancestor.csv -c BP-GOTERM.txt -t goterm
./app_da.py -i ./../data/20150503/BP/CDS-H2-BP.csv -g ./../result/BP_descendant_ancestor.csv -c BP-GOTERM.txt -t goterm
./app_da.py -i ./../data/20150503/BP/FL-7-BP.csv -g ./../result/BP_descendant_ancestor.csv -c BP-GOTERM.txt -t goterm
./app_da.py -i ./../data/20150503/BP/FL-H1-BP.csv -g ./../result/BP_descendant_ancestor.csv -c BP-GOTERM.txt -t goterm
./app_da.py -i ./../data/20150503/BP/FL-H2-BP.csv -g ./../result/BP_descendant_ancestor.csv -c BP-GOTERM.txt -t goterm
./app_da.py -i ./../data/20150503/BP/FLM-7-BP.csv -g ./../result/BP_descendant_ancestor.csv -c BP-GOTERM.txt -t goterm
./app_da.py -i ./../data/20150503/BP/FLM-H1-BP.csv -g ./../result/BP_descendant_ancestor.csv -c BP-GOTERM.txt -t goterm
./app_da.py -i ./../data/20150503/BP/FLM-H2-BP.csv -g ./../result/BP_descendant_ancestor.csv -c BP-GOTERM.txt -t goterm
./app_da.py -i ./../data/20150503/CC/CDS-7-CC.csv -g ./../result/CC_descendant_ancestor.csv -c CC-GOTERM.txt -t goterm
./app_da.py -i ./../data/20150503/CC/CDS-H1-CC.csv -g ./../result/CC_descendant_ancestor.csv -c CC-GOTERM.txt -t goterm
./app_da.py -i ./../data/20150503/CC/CDS-H2-CC.csv -g ./../result/CC_descendant_ancestor.csv -c CC-GOTERM.txt -t goterm
./app_da.py -i ./../data/20150503/CC/FL-7-CC.csv -g ./../result/CC_descendant_ancestor.csv -c CC-GOTERM.txt -t goterm
./app_da.py -i ./../data/20150503/CC/FL-H1-CC.csv -g ./../result/CC_descendant_ancestor.csv -c CC-GOTERM.txt -t goterm
./app_da.py -i ./../data/20150503/CC/FL-H2-CC.csv -g ./../result/CC_descendant_ancestor.csv -c CC-GOTERM.txt -t goterm
./app_da.py -i ./../data/20150503/CC/FLM-7-CC.csv -g ./../result/CC_descendant_ancestor.csv -c CC-GOTERM.txt -t goterm
./app_da.py -i ./../data/20150503/CC/FLM-H1-CC.csv -g ./../result/CC_descendant_ancestor.csv -c CC-GOTERM.txt -t goterm
./app_da.py -i ./../data/20150503/CC/FLM-H2-CC.csv -g ./../result/CC_descendant_ancestor.csv -c CC-GOTERM.txt -t goterm
./app_da.py -i ./../data/20150503/MF/CDS-7-MF.csv -g ./../result/MF_descendant_ancestor.csv -c MF-GOTERM.txt -t goterm
./app_da.py -i ./../data/20150503/MF/CDS-H1-MF.csv -g ./../result/MF_descendant_ancestor.csv -c MF-GOTERM.txt -t goterm
./app_da.py -i ./../data/20150503/MF/CDS-H2-MF.csv -g ./../result/MF_descendant_ancestor.csv -c MF-GOTERM.txt -t goterm
./app_da.py -i ./../data/20150503/MF/FL-7-MF.csv -g ./../result/MF_descendant_ancestor.csv -c MF-GOTERM.txt -t goterm
./app_da.py -i ./../data/20150503/MF/FL-H1-MF.csv -g ./../result/MF_descendant_ancestor.csv -c MF-GOTERM.txt -t goterm
./app_da.py -i ./../data/20150503/MF/FL-H2-MF.csv -g ./../result/MF_descendant_ancestor.csv -c MF-GOTERM.txt -t goterm
./app_da.py -i ./../data/20150503/MF/FLM-7-MF.csv -g ./../result/MF_descendant_ancestor.csv -c MF-GOTERM.txt -t goterm
./app_da.py -i ./../data/20150503/MF/FLM-H1-MF.csv -g ./../result/MF_descendant_ancestor.csv -c MF-GOTERM.txt -t goterm
./app_da.py -i ./../data/20150503/MF/FLM-H2-MF.csv -g ./../result/MF_descendant_ancestor.csv -c MF-GOTERM.txt -t goterm
